<?php
// ONLY COPY THIS TEMPLATE! DO NOT EDIT THIS FILE!
session_start();
require_once "../../Templates/header_view.php";
require_once "../../Controllers/Database.php";
require_once "../../Controllers/Functions.php";
setTitle("Classroom");
$db = new Database();
$date = new Date();
$table_name = "My Class";


allow_specific_designation_only(["TEACHER", "DEVELOPER", "STUDENT"]);
if(isset($_SESSION['class_id'])){
    $class_id = $_SESSION['class_id'];
}
// Add your filter functionality here.
// $filter_department = null;
// if (isset($_GET["selected_department"])) {
//   $filter_department = $_GET["selected_department"];
// }
// End of filter functionality here.
?>

<!-- Add required files here. -->
<?php require_once "../../Templates/sidebar.php"; ?>
<?php //require_once("./ -add.php"); ?>
<?php //require_once("./ -edit.php"); ?>
<?php //require_once("./ -delete.php"); ?>
<!-- End of required files here. -->


<div class="main-content w-100">

<!-- This will show success and failed cards -->
  <?php
  if (isset($_SESSION["success"])) { ?>
    <div class="alert alert-success text-success">
      <?php
      echo $_SESSION["success"];
      unset($_SESSION["success"]);
      ?>
    </div> <?php
          }
            ?>

  <?php
  if (isset($_SESSION["failed"])) { ?>
    <div class="alert alert-danger text-danger">
    <?php
        echo $_SESSION["failed"];
        unset($_SESSION["failed"]);
        ?>
      </div> 
      <?php
        }
        ?>
<!-- End of success and failed cards -->


<!-- This page should only be seen by user type admin -->
    <div>
        <?php //require_once "./template-filters.php"; ?>
    </div>
    <!-- Tabs at the top of the data table. -->
    <!-- Change the class of the i tag using bootstrap icons. -->
    <!-- Add the title which will serve as the title shown when tooltip is icon is hovered -->
    <!-- <div>
        <ul class="nav nav-tabs flex-row justify-content-start">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href=""><i class="" data-toggle="tooltip" data-placement="top" title=""></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href=""><i class="" data-toggle="tooltip" data-placement="top" title=""></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=""><i class="" data-toggle="tooltip" data-placement="top" title=""></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=""><i class="" data-toggle="tooltip" data-placement="top" title=""></i></a>
            </li>
        </ul>
    </div> -->
    <!-- End of tabs at the top of the data table. -->
</div>

<h4 class="my-2">Classes</h4>
    <!-- Query for class details -->
    <div class="row equal">
        <?php
        $db->query("SELECT
        `classes`.`id`,
        `classes`.`user_id`,
        `users`.`first_name`,
        `users`.`middle_name`,
        `users`.`last_name`,
        `users`.`profile_file_name` AS profile_file_name,
        `classes`.`section_id`,
        `section`.`section_name`,
        `classes`.`class_code`,
        `classes`.`class_name`
        FROM
        `classes`,
        `users`,
        `section`
        WHERE
        `classes`.`user_id` = `users`.`id` AND `classes`.`section_id` = `section`.`id` AND `classes`.`id`='{$class_id}';");
        $db->execute();
        $result_set = $db->fetch();
        $db->closeStmt();
        ?>

        <div class="card text-dark" style="background: white; border-left: #D4AF37 solid 8px;">
          <div class="card-body">
              <h6 class="card-title" style="max-width:10rem;"><?= $result_set["class_code"]." | ".$result_set["class_name"] ?></h6>
              <h7 class="card-title"><?= $result_set["section_id"]." | ".$result_set["section_name"] ?></h7>
              <p class="card-text">Professor: <?= $result_set["first_name"]." ".$result_set["middle_name"]." ".$result_set["last_name"] ?> </p>
              <div class="logo">
                  <img class="img-fluid" src="../../Assets/img/profiles/<?= $result_set["profile_file_name"] ?>"  style="float: right; height: 100px; width: 100px; border-radius: 50%; border: 2px solid #D4AF37; margin-top: 15px;">
                  </a>    
              </div>
          </div>
        </div>
      
        <!-- Query for class post -->
        <div class="accordion" id="accordionExample">
        <?php 
             $db->query("SELECT
             `classes`.`id`,
             `classes`.`user_id`,
             `users`.`first_name`,
             `users`.`middle_name`,
             `users`.`last_name`,
             `users`.`profile_file_name`,
             `classes`.`section_id`,
             `section`.`section_name`,
             `classes`.`class_code`,
             `classes`.`class_name`
         FROM
             `classes`,
             `users`,
             `section`
         WHERE
             `classes`.`user_id` = `users`.`id` AND `classes`.`section_id` = `section`.`id`;");
              $db->execute();
              $result = $db->resultSet();
              $db->closeStmt();
              foreach ($result as $row){
                $id = $date->getYear() . "-" . randomWord();
              ?>
                <div class="accordion-item">
              <h2 class="accordion-header" id="<?= $id?>">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Accordion Item #2
                </button>
              </h2>
              <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                </div>
              </div>
            </div>
            <?php
               } ;
            ?>
            </div>
            </div>
              </div>
<script src="../../Assets/js/datatables_functions.js"></script>
</script>
</body>