<?php
// ONLY COPY THIS TEMPLATE! DO NOT EDIT THIS FILE!

$choices = ['All', '', ''];
$selected = "All";
if (isset($_GET["selected"])) $selected = $_GET["selected"];
?>
<section class="d-flex gap-2 py-3">
  </form>
  <form id="filter-form"  method="GET" class="d-flex gap-2">
    <select  class="form-select w-max" id="selected" name="selected">
      <?php foreach ($choice as $choices) : ?>
        <option <?= $selected == $choices ? "selected" : ""  ?> value="<?= $choices ?>"><?= $choices ?></option>
      <?php endforeach ?>
    </select>
  </form>
</section>

<script>
  $(document).ready(function() {
    $("#selected").change(function() {
      $("#filter-form").submit();
      console.log($("#filter-form"));
    });
  });
</script>