<?php
// ONLY COPY THIS TEMPLATE! DO NOT EDIT THIS FILE!
require_once "../../Controllers/Database.php";
require_once "../../Controllers/Functions.php";

$db = new Database();

if (isset($_POST["edit"])) {
  // $ = $_POST[""];
  $edit_class_code = $_POST["edit-class-code"];
  $edit_class_name = $_POST["edit-class-name"];
  $edit_section_id = $_POST["edit-section-id"];

  $db->query("UPDATE
  `classes`
SET
  `section_id` = '{$edit_section_id}',
  `class_code` = '{$edit_class_code}',
  `class_name` = '{$edit_class_name}'
WHERE
  1");
  $db->execute();
  $db->closeStmt();

  $_SESSION["success"] = "Data has been updated successfully.";
//   $_SESSION["failed"] = "Data is already in the database.";
}
?>

<div class="modal fade modal-lg" id="editModal" tabindex="3" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit User</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form action="index.php" method="POST">
                <div class="modal-body">
                    <div class="row mt-2">
                        <div class="col">
                            <label for="edit-class-code">Class Code</label><br />
                            <div class="input-group">
                                <input type="text" name="edit-class-code" id="edit-class-code" class="form-control" required />
                                <span class="input-group-text border"><i class="fas fa-solid fa-address-card"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col">
                            <label for="edit-class-name">Class Name</label><br />
                            <div class="input-group">
                                <input type="text" name="edit-class-name" id="edit-class-name" class="form-control" required />
                                <span class="input-group-text border"><i class="fas fa-solid fa-address-card"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <label for="edit-section-id">Section Name</label><br />
                        <div class="input-group">
                            <select name="edit-section-id" id="edit-section-id" class="form-select" required>
                                <option value="" selected="true" disabled="disabled"></option>
                                <?php
                                            $db->query("SELECT `id`,`section_name` FROM `section`;"); $db->execute(); $status_query = $db->resultSet(); $db->closeStmt(); foreach ($status_query as $row) { ?>
                                <option value="<?= $row->id ?>"><?= $row->section_name ?></option>
                                <?php 
                                            };
                                            ?>
                            </select>
                            <span class="input-group-text"><i class="fas fa-solid fa-building-user"></i></span>
                        </div>
                    </div>

                </div>
                <!-- modal-body closing -->
                <div class="modal-footer w-100">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit"  value="Submit" name="edit" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
