<?php
// ONLY COPY THIS TEMPLATE! DO NOT EDIT THIS FILE!
require_once "../../Controllers/Database.php";
require_once "../../Controllers/Functions.php";

$db = new Database();

if (isset($_POST["edit-class-announcements"])) {
  // $ = $_POST[""];
  $edit_content = preg_replace('/\s+/S', " ", $_POST["edit-content"]);
  $edit_section_id = $_POST["edit-section-id"];

  $db->query("UPDATE
  `class_announcement`
SET
  `section_id` = '{$edit_section_id}',
  `content` = '{$edit_content}'
WHERE
  `id`={$_POST["edit-id"]}");
  $db->execute();
  $db->closeStmt();

  $_SESSION["success"] = "Data has been updated successfully.";
//   $_SESSION["failed"] = "Data is already in the database.";
}
?>

<div class="modal fade modal-lg" id="editModal" tabindex="3" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit Class Announcement</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form action="./class-announcements-index.php" method="POST">
                <div class="modal-body">

                    <div class="row mt-2">
                        <div class="col">
                            <label for="edit-content">Content</label><br />
                            <input type="hidden" name="edit-id" id="edit-id" class="form-control" />
                            <textarea type="text" rows="4" class="form-control" name="edit-content" id="edit-content" required></textarea>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <label for="add-section-id">Section ID</label><br />
                        <div class="input-group">
                            <select name="edit-section-id" id="edit-section-id" class="form-select" required>
                                <option value="" selected="true" disabled="disabled"></option>
                                <?php
                                $db->query("SELECT `id`,`section_name` FROM section;"); $db->execute(); $status_query = $db->resultSet(); $db->closeStmt(); foreach ($status_query as $row) { ?>
                                <option value="<?= $row->id ?>"><?= $row->section_name ?></option>
                                <?php 
                                };
                                ?>
                            </select>
                            <span class="input-group-text"><i class="fas fa-solid fa-building-user"></i></span>
                        </div>
                    </div>

                    
                </div>
                <!-- modal-body closing -->
                <div class="modal-footer w-100">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit"  value="Submit" name="edit-class-announcements" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
