<?php
// ONLY COPY THIS TEMPLATE! DO NOT EDIT THIS FILE!
session_start();
require_once "../../Templates/header_view.php";
require_once "../../Controllers/Database.php";
require_once "../../Controllers/Functions.php";
setTitle("Class Announcements");
$db = new Database();
$table_name = "Class Announcements";

allow_specific_designation_only(["TEACHER", "DEVELOPER"]);

// Add your filter functionality here.
// $filter = null;
// if (isset($_GET["selected"])) {
//   $filter = $_GET["selected"];
// }
// End of filter functionality here.
?>

<!-- Add required files here. -->
<?php require_once "../../Templates/sidebar.php"; ?>
<?php require_once("./class-announcements-add.php"); ?>
<?php require_once("./class-announcements-edit.php"); ?>
<?php require_once("./class-announcements-delete.php"); ?>
<!-- End of required files here. -->


<div class="main-content w-100">

<!-- This will show success and failed cards -->
  <?php
  if (isset($_SESSION["success"])) { ?>
    <div class="alert alert-success text-success">
      <?php
      echo $_SESSION["success"];
      unset($_SESSION["success"]);
      ?>
    </div> <?php
          }
            ?>

  <?php
  if (isset($_SESSION["failed"])) { ?>
    <div class="alert alert-danger text-danger">
    <?php
        echo $_SESSION["failed"];
        unset($_SESSION["failed"]);
        ?>
      </div> 
      <?php
        }
        ?>
<!-- End of success and failed cards -->


<!-- This page should only be seen by user type admin -->
  <h4 class="py-2"><?= $table_name ?></h4>
    <div>
        <?php //require_once "./class-announcements-filters.php"; ?>
    </div>
    <!-- Tabs at the top of the data table. -->
    <!-- Change the class of the i tag using bootstrap icons. -->
    <!-- Add the title which will serve as the title shown when tooltip is icon is hovered -->
    <div>
        <ul class="nav nav-tabs flex-row justify-content-start">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="./index.php"><i class="fa-solid fa-chalkboard-user" data-toggle="tooltip" data-placement="top" title=""></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="./class-announcements-index.php"><i class="fa-solid fa-bullhorn" data-toggle="tooltip" data-placement="top" title="Class Announcement"></i></a>
            </li>
        </ul>
    </div>
    <!-- End of tabs at the top of the data table. -->
  
    <div class="p-4 shadow-sm table-container">
        <table id="datatable-main" class="table table-striped" style="width: 100%;"></table>
    </div>
</div>


<?php
// Insert the sql query here.
$query = "SELECT
`id`,
`teacher_id`,
`section_id`,
`content`,
`timestamp`
FROM
`class_announcement`
WHERE
1";

// Modify this part if you want to set a filter functionality. 
// It will concatenate a sql query at the end of the first query.
// if ($filter && $filter != "All") {
//     $filter_query = $filter_query . " AND user_department.department_name='{$filter}'";
// }
// End of filter functionality here.

$db->query($query);
$db->execute();
$db->closeStmt();
$table_data = [
    "rows" => json_encode($db->resultSet()),
    "columns" => json_encode([
        // This will encode the values of from the query to the columns and rows of the table.
        // The first variable is the column name in the sql query/table, 
        // The second one is the name of the table head of the data table.  
        // Example: "id" => "ID", 
        "id" => "ID",
        "teacher_id" => "Teacher ID",
        "section_id" => "Section ID",
        "timestamp" => "Date",
        "content" => "Announcement",
    ]),
];
?>


<script src="../../Assets/js/datatables_functions.js"></script>
<script>
  $(document).ready(function() {
    var tableName = "<?= $table_name ?>";
    var editor;
    var columns = JSON.parse('<?php print_r($table_data["columns"]); ?>');
    var rows = ObjectsToDataTableArray(JSON.parse('<?php print_r($table_data["rows"]); ?>'), Object.keys(columns));
    var mainDataTableId = "#datatable-main";
    showDataTable(rows, columns, mainDataTableId, tableName);

    // Pass the data to the edit page input form
    $(mainDataTableId).on('click', 'td.editor-edit', function(e) {
      var rowObject = JSON. parse($(this).attr("rowdata"));
      // This will send the data that is read from the table to the 
      // dedicated input tags in the edit form of this page.
      // Example: $("#edit-id").val(rowObject['id']);
      // $("#").val(rowObject['']);
      $("#edit-id").val(rowObject['id']);
      $("#edit-content").val(rowObject['content']);
      $("#edit-section-id").val(rowObject['section_id']);
    });

    // Delete record
    $(".delete-button").click(function(){
      var id = $(this).closest("tr").get(0).id;
      // This will send the data that is read from the table to the 
      // dedicated input tags in the edit form of this page.
      // Example: $("#delete-id").val(id);
      // $("#").val(rowObject['']);
      $("#delete-id").val(id);
    });

    console.log(columns);
    var columnArr = Object.keys(columns);

    // Store Data into the edit button
    $("#datatable-main tbody tr").each(function() {
      var element = $(this);
      console.log(element);
      var rowObject = {};
      var i = 0;
      element.children('td').each(function () {
        var textData = $(this).text().trim();
        rowObject[columnArr[i]] = textData;
        // if(i == [number of columns])
        if(i == 5){
          $(this).attr("rowdata",JSON.stringify(rowObject));
        }
        i++;
      });
    });

    // Make the data invisible from table
    // $("#datatable-main tbody tr td:nth-child(11)").each(function() {
    //   var tdData = $(this).text();
    //   $(this).html(
    //     `
    //     <span class="invisible">${tdData}</span>
    //     `
    //     );
    //   }); 
    
    // $("#datatable-main tbody tr td:nth-child(12)").each(function() {
    // var tdData = $(this).text();
    // $(this).html(
    //   `
    //   <span class="invisible">${tdData}</span>
    //   `
    //   );
    // }); 
    // End of making data invisible from table


  }); 
</script>
</body>