<?php
// ONLY COPY THIS TEMPLATE! DO NOT EDIT THIS FILE!
require_once "../../Controllers/Database.php";
require_once "../../Controllers/Functions.php";

$db = new Database();

if (isset($_POST["edit"])) {
  // $ = $_POST[""];

//   $db->query("");
//   $db->execute();
//   $db->closeStmt();

//   $_SESSION["success"] = "Data has been updated successfully.";
//   $_SESSION["failed"] = "Data is already in the database.";
}
?>

<div class="modal fade modal-lg" id="editModal" tabindex="3" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit User</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form action="index.php" method="POST">
                <div class="modal-body">
                    <!-- Include id for the input forms using the id in the index form edit button-->
                    <!-- Example of normal input form -->
                    <!-- <div class="row mt-2">
                        <div class="col">
                            <label for="fname">First Name</label><br />
                            <div class="input-group">
                                <input type="hidden" name="user-id" id="user-id" class="form-control" />
                                <input type="text" name="first-name" id="first-name" class="form-control" />
                                <span class="input-group-text border"><i class="fas fa-solid fa-address-card"></i></span>
                            </div>
                        </div>
                    </div> -->

                    <!-- Example of drop down input form -->
                    <!-- <div class="row mt-2">
                        <div class="col">
                            <label for="gender">Gender</label><br />
                            <div class="input-group">
                                <select name="gender" id="user-gender" class="form-control">
                                    <option value="" selected disabled></option>
                                    <option value="male">MALE</option>
                                    <option value="female">FEMALE</option>
                                </select>
                                <span class="input-group-text border"><i class="fas fa-solid fa-mars-and-venus"></i></span>
                            </div>
                        </div>
                    </div> -->

                  
                    
                    <!-- Example a drop down input wherein the data comes from sql query -->
                    <!-- <div class="row mt-2">
                        <label for="status">Department</label><br />
                        <div class="input-group">
                            <select name="department" id="department-id" class="form-select">
                                <option value="" selected="true" disabled="disabled"></option>
                                <?php
                //   $db->query("SELECT `id`,`department_name` FROM user_department;"); $db->execute(); $status_query = $db->resultSet(); $db->closeStmt(); foreach ($status_query as $row) { ?>
                                <option value="<= $row->id?>"><= $row->department_name?></option>
                                <?php
                //   };
                  ?>
                            </select>
                            <span class="input-group-text"><i class="fas fa-solid fa-building-user"></i></span>
                        </div>
                    </div> -->

                </div>
                <!-- modal-body closing -->
                <div class="modal-footer w-100">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit"  value="Submit" name="edit" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
